services:
  sysops-console:
    build: .
    container_name: portfolio-sysops
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: "no"
    # Le conteneur s'arrÃªtera si vous faites Ctrl+C, c'est voulu pour un outil ponctuel.
